spring:
  data:
    mongodb:
 #     authentication-database:
      username: chandan
      password: root
      database: noteDb
      port: 27017
      host: localhost
  application:
    name: note-service
server:
  port: 8082
